# Generated by Django 4.2.7 on 2023-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
