# Generated by Django 4.2.7 on 2023-11-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_rename_payment_id_cartitem_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.payment",
            ),
        ),
    ]
