# Generated by Django 4.2.7 on 2023-11-26 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_paid_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        100, message="100원 부터 결제가 가능합니다."
                    )
                ]
            ),
        ),
    ]
