# Generated by Django 4.2.7 on 2023-11-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_product_payment_created_at_payment_updated_at_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
