# Generated by Django 4.2.7 on 2023-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aichatlog",
            name="messages",
            field=models.JSONField(default=list),
        ),
    ]
