# Generated by Django 4.2.7 on 2023-11-10 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="agree_terms",
        ),
    ]
