# Generated by Django 4.2.7 on 2023-11-23 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="readings_num",
            new_name="reading_nums",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="words_num",
            new_name="word_nums",
        ),
    ]
