# Generated by Django 4.2.7 on 2023-12-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_reading_coin_user_coin_remove_user_chat_coin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="coin",
            field=models.SmallIntegerField(default=100),
        ),
    ]
