# Generated by Django 4.2.7 on 2023-11-23 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="content",
            new_name="term",
        ),
    ]
