# Generated by Django 4.2.7 on 2023-11-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=30)),
                ("you", models.CharField(max_length=30)),
                ("me", models.CharField(max_length=30)),
                ("action", models.TextField()),
            ],
        ),
    ]
