# Generated by Django 4.2.7 on 2023-11-16 06:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("english", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Difficult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=30)),
                ("you", models.CharField(max_length=30)),
                ("me", models.CharField(max_length=30)),
                ("action", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="select",
            name="passage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selects",
                to="english.readingpassage",
            ),
        ),
    ]
